// Single source of truth for Luna's animated GIFs.
//
// Each mood + skin maps to its own asset so callers (paywall, Home
// nook, Me room, auth screens, onboarding, profile, chat avatar,
// etc.) can render the right expression + skin with one consistent
// API. The skin defaults to the user's currently-chosen avatar via
// the `useLunaSkin()` hook.
//
// Use:
//   import { lunaSource, useLunaSkin } from '../lib/luna-source';
//   const skin = useLunaSkin();
//   <Image source={lunaSource(mood, skin)} style={{ width, height }} />
//
// When in doubt, default to 'idle' + 'default' (original tan cat).

import { useUserStore } from '../store/userStore';

export type LunaMood = 'idle' | 'happy' | 'sad' | 'sleep' | 'walk' | 'lick';

// `require` returns a numeric asset id at bundle time — Metro
// statically resolves these, so we keep one require per (skin, mood)
// combo and pick at runtime. New moods or skins get a new asset +
// a new branch.
//
// 'walk' is the animated GIF that shows the cat MOVING on its
// little feet — used by the Me-tab pacing loop. 'lick' is the
// grooming animation; we inject it as a brief beat during task
// completion + focus start + occasional Me-tab idle moments so the
// cat reads as a living creature with personality quirks instead
// of just rotating through static emotions.
const BASE = {
  idle: require('../assets/luna-idle.gif'),
  happy: require('../assets/luna-happy.gif'),
  sad: require('../assets/luna-sad.gif'),
  sleep: require('../assets/luna-sleep.gif'),
  walk: require('../assets/luna-walk.gif'),
  lick: require('../assets/luna-lick.gif'),
} as const;

// Each skin has its own recolored copy of every mood. Generated by
// the Python script at scripts/regen-skin-cats.py from the base
// GIFs — HLS-shifting body-hue pixels toward the skin's primary
// while preserving each pixel's original lightness so shading
// survives. See lib/skin-preview.ts for the still-frame version
// used by the picker.
const CREAM = {
  idle: require('../assets/skins/luna-cream-idle.gif'),
  happy: require('../assets/skins/luna-cream-happy.gif'),
  sad: require('../assets/skins/luna-cream-sad.gif'),
  sleep: require('../assets/skins/luna-cream-sleep.gif'),
  walk: require('../assets/skins/luna-cream-walk.gif'),
  lick: require('../assets/skins/luna-cream-lick.gif'),
} as const;

const PLUM = {
  idle: require('../assets/skins/luna-plum-idle.gif'),
  happy: require('../assets/skins/luna-plum-happy.gif'),
  sad: require('../assets/skins/luna-plum-sad.gif'),
  sleep: require('../assets/skins/luna-plum-sleep.gif'),
  walk: require('../assets/skins/luna-plum-walk.gif'),
  lick: require('../assets/skins/luna-plum-lick.gif'),
} as const;

const MOSS = {
  idle: require('../assets/skins/luna-moss-idle.gif'),
  happy: require('../assets/skins/luna-moss-happy.gif'),
  sad: require('../assets/skins/luna-moss-sad.gif'),
  sleep: require('../assets/skins/luna-moss-sleep.gif'),
  walk: require('../assets/skins/luna-moss-walk.gif'),
  lick: require('../assets/skins/luna-moss-lick.gif'),
} as const;

const TERRA = {
  idle: require('../assets/skins/luna-terra-idle.gif'),
  happy: require('../assets/skins/luna-terra-happy.gif'),
  sad: require('../assets/skins/luna-terra-sad.gif'),
  sleep: require('../assets/skins/luna-terra-sleep.gif'),
  walk: require('../assets/skins/luna-terra-walk.gif'),
  lick: require('../assets/skins/luna-terra-lick.gif'),
} as const;

const MIST = {
  idle: require('../assets/skins/luna-mist-idle.gif'),
  happy: require('../assets/skins/luna-mist-happy.gif'),
  sad: require('../assets/skins/luna-mist-sad.gif'),
  sleep: require('../assets/skins/luna-mist-sleep.gif'),
  walk: require('../assets/skins/luna-mist-walk.gif'),
  lick: require('../assets/skins/luna-mist-lick.gif'),
} as const;

const MIDNIGHT = {
  idle: require('../assets/skins/luna-midnight-idle.gif'),
  happy: require('../assets/skins/luna-midnight-happy.gif'),
  sad: require('../assets/skins/luna-midnight-sad.gif'),
  sleep: require('../assets/skins/luna-midnight-sleep.gif'),
  walk: require('../assets/skins/luna-midnight-walk.gif'),
  lick: require('../assets/skins/luna-midnight-lick.gif'),
} as const;

const SKIN_SOURCES: Record<string, typeof BASE> = {
  default: BASE,
  original: BASE,
  cream: CREAM,
  plum: PLUM,
  moss: MOSS,
  terra: TERRA,
  mist: MIST,
  midnight: MIDNIGHT,
};

/**
 * Returns the require()'d asset for a given mood + skin. Unknown
 * skin ids fall back to the base cat; unknown moods fall back to
 * idle. Second arg defaults to 'default' so old call sites keep
 * working (they render the original cat).
 */
export const lunaSource = (
  mood: LunaMood = 'idle',
  skinId: string = 'default',
) => {
  const skin = SKIN_SOURCES[skinId] ?? BASE;
  return skin[mood] ?? skin.idle;
};

/**
 * Reactive hook — returns the user's currently-selected avatar id
 * so components can pass it to lunaSource without threading it
 * through props. Re-renders when the user picks a new skin in the
 * profile picker.
 */
export const useLunaSkin = (): string => {
  return useUserStore((s) => s.avatar) || 'default';
};
