// Single source of truth for the skin-preview PNG per skin id.
// These are recolored still-frame renders of the base luna sprite —
// each skin gets its own PNG so the picker + profile personal cell
// can show ACTUAL color variation instead of the same tan cat with
// a different label under it.
//
// Generated by scripts/regen-skin-previews.py from luna-idle.gif
// frame 0 with per-skin HLS remapping (see the script for the
// hue / saturation / lightness math). To regenerate, edit the SKINS
// dict in that script and re-run — the PNGs are checked in so this
// module works offline.

const SOURCES = {
  default: require('../assets/skins/luna-original.png'),
  original: require('../assets/skins/luna-original.png'),
  cream: require('../assets/skins/luna-cream.png'),
  plum: require('../assets/skins/luna-plum.png'),
  moss: require('../assets/skins/luna-moss.png'),
  terra: require('../assets/skins/luna-terra.png'),
  mist: require('../assets/skins/luna-mist.png'),
  midnight: require('../assets/skins/luna-midnight.png'),
} as const;

export type SkinId = keyof typeof SOURCES;

/**
 * Returns the require()'d image asset id for a skin. Falls back to
 * the original cat if the id isn't recognized — same graceful path
 * lunaSource() takes for unknown moods.
 */
export const skinPreview = (skinId: string | undefined) => {
  const key = (skinId ?? 'default') as SkinId;
  return SOURCES[key] ?? SOURCES.default;
};
